In [1]:
import torch
import pandas as pd 
import numpy as np
print (torch.__version__)

2.7.1+cu118


In [2]:
scaler=torch.tensor(7)
print (scaler)

tensor(7)


In [3]:
vector=torch.tensor([1.0,2.0,3.0])
print (vector)  

tensor([1., 2., 3.])


In [4]:
vector.shape
vector.ndim

1

In [5]:
matrix=torch.tensor([[1,2,3],[4,5,6]])
matrix[0]

tensor([1, 2, 3])

In [6]:
print (torch.cuda.is_available())

True


In [7]:
##scalar
scalar=torch.tensor(4)
scalar

tensor(4)

In [8]:
scalar.ndim

0

In [9]:
scalar.shape

torch.Size([])

In [10]:
scalar.item()

4

In [11]:
vector=torch.tensor([1,3,6,5])

In [12]:
vector.shape

torch.Size([4])

In [13]:
vector.ndim

1

In [14]:
matrix=torch.tensor([[1,2,3],[4,5,6]])
matrix

tensor([[1, 2, 3],
        [4, 5, 6]])

In [15]:
matrix.ndim

2

In [16]:
matrix.shape

torch.Size([2, 3])

In [17]:
tensor= torch.tensor([[[1,3,3,3],[4,4,5,6],[7,8,8,8]]])
tensor.shape

torch.Size([1, 3, 4])

In [18]:
tensor= torch.tensor([[[1,2,3,4],[5,6,7,8],[9,10,11,12],[13,14,15,16],[17,18,19,20]],
                      [[21,22,23,24],[25,26,27,28],[29,30,31,32],[33,34,35,36],[37,38,39,40]],
                      [[41,42,43,44],[45,46,47,48],[49,50,51,52],[53,54,55,56],[57,58,59,60]]])
tensor.shape

torch.Size([3, 5, 4])

In [19]:
tensor[0,4,3]

tensor(20)

In [23]:
random_tensor=torch.rand(3,5,4)
random_tensor

tensor([[[0.5358, 0.3195, 0.4232, 0.1822],
         [0.2495, 0.3117, 0.2015, 0.4343],
         [0.2156, 0.5985, 0.1774, 0.3113],
         [0.6078, 0.3470, 0.4449, 0.4075],
         [0.1554, 0.9827, 0.8546, 0.1768]],

        [[0.7756, 0.5369, 0.7843, 0.4744],
         [0.5272, 0.6638, 0.7168, 0.6591],
         [0.3470, 0.9262, 0.1650, 0.0104],
         [0.9658, 0.5172, 0.5727, 0.7197],
         [0.4472, 0.9075, 0.2154, 0.9873]],

        [[0.9486, 0.1033, 0.0676, 0.4370],
         [0.7825, 0.3463, 0.8410, 0.8274],
         [0.4776, 0.8176, 0.7552, 0.0711],
         [0.2263, 0.6182, 0.5939, 0.0771],
         [0.7207, 0.7320, 0.5797, 0.0752]]])

In [24]:
random_tensor[2,2,1]

tensor(0.8176)

In [26]:
range=torch.arange(0,140)
range

tensor([  0,   1,   2,   3,   4,   5,   6,   7,   8,   9,  10,  11,  12,  13,
         14,  15,  16,  17,  18,  19,  20,  21,  22,  23,  24,  25,  26,  27,
         28,  29,  30,  31,  32,  33,  34,  35,  36,  37,  38,  39,  40,  41,
         42,  43,  44,  45,  46,  47,  48,  49,  50,  51,  52,  53,  54,  55,
         56,  57,  58,  59,  60,  61,  62,  63,  64,  65,  66,  67,  68,  69,
         70,  71,  72,  73,  74,  75,  76,  77,  78,  79,  80,  81,  82,  83,
         84,  85,  86,  87,  88,  89,  90,  91,  92,  93,  94,  95,  96,  97,
         98,  99, 100, 101, 102, 103, 104, 105, 106, 107, 108, 109, 110, 111,
        112, 113, 114, 115, 116, 117, 118, 119, 120, 121, 122, 123, 124, 125,
        126, 127, 128, 129, 130, 131, 132, 133, 134, 135, 136, 137, 138, 139])

In [27]:
range1=torch.arange(1,100,10)
range1

tensor([ 1, 11, 21, 31, 41, 51, 61, 71, 81, 91])

In [28]:
alike=torch.zeros_like(range1)
alike

tensor([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [29]:
import torch
x=torch.arange(1,10)
x

tensor([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [34]:
x=x.reshape(3,3)
x

tensor([[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]])